apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weave_placeholder
# this file can be used to add/replace parts of the base spec 
# by simply introducing the same structure.
# note: if you want to edit instead of replacing things
# you are better off with json 6902 patches, similar to 
# bns-ingress-patch.yaml
# consult https://github.com/kubernetes-sigs/kustomize/tree/6f566d7a38cffcbb74a2ca2d762f8fbd65055d44/examples/ldap
# for a good example
spec:
  template:
    spec:
      serviceAccountName: bns  
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000        
      initContainers:
      - name: tm-gen-validator
        imagePullPolicy: Always
        image: iov1/tendermint:0.31.5
        env:
          - name: TMHOME
            value: /data/tendermint
        command:
          - bash
          - "-c"
        args:
          - |
            set -exo pipefail
            if [ ! -f ${TMHOME}/.INITIALISED ]; then
              mkdir -p /data/bns
              mkdir -p ${TMHOME}/tmp
              tendermint init

              cp -f /etc/tendermint/genesis.json ${TMHOME}/config/genesis.json
              cat ${TMHOME}/config/genesis.json > ${TMHOME}/config/genesis.json_work

              # generate new key and add to genesis and local prival signer
              tendermint gen_validator > ${TMHOME}/config/priv_validator_work.json
              cat ${TMHOME}/config/priv_validator_work.json | jq ".Key" > ${TMHOME}/config/priv_validator_key.json
              cat ${TMHOME}/config/priv_validator_work.json | jq ".LastSignState" > ${TMHOME}/data/priv_validator_state.json
              cat ${TMHOME}/config/priv_validator_key.json | jq ".pub_key" | jq ". as \$k | {pub_key: \$k, power: \"10\", name: \"validator\"}" > ${TMHOME}/tmp/pub_validator.json
              cat ${TMHOME}/config/genesis.json_work | jq ".validators |= .+ [$(cat ${TMHOME}/tmp/pub_validator.json)]" > ${TMHOME}/config/genesis.json

              rm -rf ${TMHOME}/tmp
              rm -f  ${TMHOME}/config/genesis.json_work
              chmod 444 ${TMHOME}/config/genesis.json

              touch ${TMHOME}/.INITIALISED
            fi
            rm -f /socks/app.sock
        volumeMounts:
          - name: tmdir
            mountPath: "/data"
          - mountPath: /etc/tendermint/genesis.json
            name: tm-initialization
            subPath: genesis.json
            readOnly: true
          - mountPath: /socks
            name: socksdir
      containers:
      - name: tendermint
        resources:
          limits:
            cpu: 1500m
            memory: 4Gi
          requests:
            cpu: 750m
            memory: 2Gi
        readinessProbe:
          exec:
            command:
              - sh
              - -o
              - pipefail
              - -ec
              - 'curl -s --fail http://localhost:26657/abci_info | jq --exit-status ".result.response"'
          failureThreshold: 999999
          periodSeconds: 20
          initialDelaySeconds: 40
      - name: weave_placeholder
        resources:
          limits:
            cpu: 1500m
            memory: 12Gi
          requests:
            cpu: 750m
            memory: 8Gi
