apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bns-faucet
  annotations:
  labels:
    app: bns-faucet
    component: api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bns-faucet
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bns-faucet
        component: api
    spec:
      containers:
      - name: bns-faucet
        image: iov1/iov-faucet:v0.5.1
        imagePullPolicy: Always
        env:
        - name: FAUCET_PORT
          value: '8080'
        - name: FAUCET_MNEMONIC
          valueFrom:
            secretKeyRef:
              name: bns-faucet-settings
              key: FAUCET_MNEMONIC
        - name: FAUCET_CREDIT_AMOUNT_TKN
          value: '10'
        - name: FAUCET_REFILL_FACTOR
          value: '8'
        - name: FAUCET_REFILL_THRESHOLD
          value: '20'
        args:
          - start
          - bns
          - ws://bns.default.svc.cluster.local:26657
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 3
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 2
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsGroup: 2000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app: bns-faucet
    component: api
  name: bns-faucet
spec:
  selector:
    app: bns-faucet
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
