bases:
  - ../base
patchesStrategicMerge:
  - bns-validator.yaml
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: tendermint-bns
  path: bns-ingress-patch.yaml
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: bns-faucet
  path: bns-faucet-ingress-patch.yaml  
images:
- name: iov1/tendermint
  newTag: v0.29.1