bases:
  - ../base
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: wallet
  path: ingress-patch.yaml
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: wallet
  path: wallet-patch.yaml
configMapGenerator:
- name: wallet-conf
  files:
    - config.json
images:
- name: iov1/wallet-demo
  newName: iov1/bierzo-wallet
  newTag: v0.2.0