apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: block-metrics-db
  labels:
    app: block-metrics-db
spec:
  selector:
    matchLabels:
      app: block-metrics-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: block-metrics-db
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
      serviceAccountName: bns
      containers:
      - image: postgres:latest
        name: block-metrics-db
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: block-metrics-db-settings
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: block-metrics-db-settings
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: block-metrics-db-settings
              key: dbname
        ports:
        - containerPort: 5432
          name: block-mt-port
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: block-metrics-db-vl
      volumes:
        - name: block-metrics-db-vl
          gcePersistentDisk:
            pdName: block-metrics-db-vl
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: block-metrics-db 
  labels:
    app: block-metrics-db
spec:
  ports:
    - port: 5432
  selector:
    app: block-metrics-db
