apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: faucet
  annotations:
    kubernetes.io/ingress.class: "traefik"
    prometheus.io/probe: "true"
  labels:
    traffik-type: private
    app: faucet
spec:
  rules:
  - host: faucet.example.com
    http:
      paths:
      - backend:
          serviceName: faucet
          servicePort: http
