apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: faucet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faucet
  template:
    metadata:
      labels:
        app: faucet
    spec:
      containers:
      - name: faucet
        image: iov1/iov-faucet:v0.5.1
        imagePullPolicy: Always
        env:
        - name: FAUCET_PORT
          value: '8080'
        - name: FAUCET_MNEMONIC
          valueFrom:
            secretKeyRef:
              name: faucet-settings
              key: FAUCET_MNEMONIC
        - name: FAUCET_CREDIT_AMOUNT_IOV
          value: '10'
        - name: FAUCET_REFILL_FACTOR
          value: '8'
        - name: FAUCET_REFILL_THRESHOLD
          value: '20'
        args:
          - start
          - bns
          - ws://weave_placeholder.default.svc.cluster.local:26657
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: faucet
spec:
  selector:
    app: faucet
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
