apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: base-faucet
spec:
  rules:
  - host: base-faucet.example.com
    http:
      paths:
      - backend:
          serviceName: base-faucet
          servicePort: http
