apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: faucet
  annotations:
    kubernetes.io/ingress.class: "traefik"
    prometheus.io/probe: "true"
  labels:
    traffic-type: private
    app: faucet
spec:
  rules:
  - host: faucet.x-dancenet.iov.one
    http:
      paths:
      - backend:
          serviceName: faucet
          servicePort: 8080
