apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tendermint-base
spec:
  rules:
  - host: base.example.com
    http:
      paths:
      - backend:
          serviceName: base
          servicePort: 26657  