apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bns-fullnode-seed
  labels:
    app: bns-fullnode-seed
    component: core
spec:
  serviceName: bns-fullnode-seed
  replicas: 1
  selector:
    matchLabels:
      app: bns-fullnode-seed
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: bns-fullnode-seed
        component: core
        clusterName: bns
    spec:
      terminationGracePeriodSeconds: 20
      restartPolicy: Always
      initContainers:
      - name: tm-init
        imagePullPolicy: IfNotPresent
        image: iov1/tendermint:v0.31.5
        env:
        - name: TMHOME
          value: /data/tendermint
        command:
          - bash
          - "-c"
        args:
          - |
            set -exo pipefail
            if [ ! -f ${TMHOME}/.INITIALISED ]; then
              mkdir -p /data/bns
              tendermint init
              touch ${TMHOME}/.INITIALISED
            fi
            rm -f /socks/app.sock
        volumeMounts:
          - mountPath: /data
            name: tmdir
          - mountPath: /socks
            name: socksdir
        resources:
          limits:
            cpu: 150m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      containers:
      - name: bns
        imagePullPolicy: IfNotPresent
        image: iov1/bnsd:v0.21.0
        args:
          - -home=/data/bns
          - start
          - -bind=unix:///socks/app.sock
          - '-min_fee=0.0001 IOV'
        volumeMounts:
          - name: socksdir
            mountPath: /socks
          - name: tmdir
            mountPath: /data/bns
            subPath: bns
        securityContext:
          readOnlyRootFilesystem: true
      - name: tendermint
        imagePullPolicy: IfNotPresent
        image: iov1/tendermint:v0.31.5
        ports:
        - containerPort: 26656
          name: p2p
        - containerPort: 26657
          name: rpc
        command:
        - bash
        - "-c"
        - |
          set -ex
          exec tendermint node  \
            --moniker="`hostname`" \
            --log_level="p2p:info,state:info,*:error" \
            --proxy_app="unix:///socks/app.sock"
        volumeMounts:
        - mountPath: /data/tendermint/config/config.toml
          name: tm-configuration
          subPath: config.toml
          readOnly: true
        - mountPath: /data/tendermint/config/genesis.json
          name: tm-genesis
          subPath: genesis.json
          readOnly: true
        - name: tmdir
          mountPath: /data/tendermint
          subPath: tendermint
        - name: socksdir
          mountPath: /socks
        - name: tm-rw-volume
          mountPath: /tmp
        securityContext:
          readOnlyRootFilesystem: true
        resources:
          limits:
            cpu: 1100m
            memory: 2.5Gi
          requests:
            cpu: 750m
            memory: 1Gi
      volumes:
      - name: tm-configuration
        configMap:
          name: seed-tendermint-config
      - name: tm-genesis
        configMap:
          name: tm-seed-init-config
      - name: socksdir
        emptyDir: {}
      - name: tm-rw-volume
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: tmdir
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: bns-fullnode-seed
  labels:
    app: bns-fullnode-seed
    component: core
spec:
  ports:
    - port: 26657
      name: rpc
  selector:
    app: bns-fullnode-seed