apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-public
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: traefik-public
    spec: 
      serviceAccountName: traefik-ingress
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - image: traefik:v1.7.4-alpine
          name: traefik-public
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
              name: http
              protocol: TCP
            - containerPort: 9443
              name: https
              protocol: TCP
            - containerPort: 8080
              name: internal
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
            - mountPath: /etc/tls-certs
              name: certs
              readOnly: true
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          args:
            - --kubernetes
            - --logLevel=INFO
            - --kubernetes.namespaces=default
            - --configfile=/config/traefik.toml
      volumes:
      - name: certs
        secret:
          secretName: traefik-public-certs
          defaultMode: 0400
      - name: config
        configMap:
          name: traefik-public-conf
          defaultMode: 0400
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-public-console
spec:
  selector:
    app: traefik-public
  ports:
    - port: 8080
      name: internal
