apiVersion: v1
kind: Service
metadata:
  name: traefik-public
  labels:
    app: traefik-public
    component: controller
spec:
  selector:
    app: traefik-public
  ports:
    - port: 80
      name: http
      targetPort: 9080
    - port: 443
      name: https
      targetPort: 9443
  type: LoadBalancer