defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":9080"
  [entryPoints.http.redirect]
  regex = "^http://(.*)/(.*)"
  replacement = "https://$1/$2"
  permanent = true
  [entryPoints.https]
  address = ":9443"
  [entryPoints.https.tls]
  [[entryPoints.https.tls.certificates]]
  certFile = "/etc/tls-certs/_.x-dancenet.iov.one.crt"
  keyFile = "/etc/tls-certs/_.x-dancenet.iov.one.key"
[kubernetes]

